languageCode = "en-us"
baseUrl = "https://uptointerpretation.com"
title = "Up to Interpretation"
theme = "github.com/Mitrichius/hugo-theme-anubis"
paginate = 10
enableRobotsTXT = true

[menu]
  [main]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = "1"

[params]
author = "Nicholas Yang"
description = "A blog on programming and other things"
copyright = "Copyright © 2023 Nicholas Yang"
highlightjs = true
rssAsSocialIcon = true