languageCode = "en-us"
baseUrl = "https://uptointerpretation.com"
title = "Up to Interpretation"
theme = "anubis"
paginate = 10
enableRobotsTXT = true

[menu]
  [main]
    identifier = "archive"
    name = "Archive"
    title = "Archive"
    url = "/posts/"
    weight = "0"

[params]
author = "Nicholas Yang"
description = "A blog on programming and other things"
copyright = "Copyright © 2022 Nicholas Yang"
highlightjs = true
rssAsSocialIcon = true